[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "project2"
version = "0.1.0"
dependencies = [
    "pandas",
    "ccxt",
    "pyyaml",
    "matplotlib",
    "pyarrow",
]

[tool.setuptools.packages.find]
where = ["src"]
