[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "src"        # package name (shows up in pip list)
version = "0.1.0"
dependencies = [
    "pandas",
    "ccxt",
    "pyyaml",
    "matplotlib",
    "pyarrow",
    "numpy",
    "gymnasium",
    "pytest"
]

[tool.setuptools]
packages = ["src"]  # <- force setuptools to install "src" as the package
